# -*- coding: utf-8 -*-
"""Comparative_LDA_NMF_BERT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nIu4LRyJj2pD0H8-PHBm0Ji3k_MPrZfl
"""

# Instalación de dependencias
!pip install gensim pyLDAvis --quiet
!pip install bertopic sentence-transformers umap-learn hdbscan --quiet
!pip install matplotlib seaborn wordcloud plotly --quiet
!pip install scikit-learn openpyxl --quiet
!pip install google-generativeai --quiet

import warnings
warnings.filterwarnings("ignore", message="datetime.datetime.utcnow")
import warnings
warnings.filterwarnings("ignore", category=DeprecationWarning)

import os, re, warnings, hashlib, json, time
from collections import defaultdict, Counter

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.cm as cm
import seaborn as sns
from wordcloud import WordCloud
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots

import spacy, spacy.cli
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import NMF
from sklearn.metrics.pairwise import cosine_similarity

import gensim
from gensim.corpora import Dictionary
from gensim.models import LdaModel
from gensim.models.coherencemodel import CoherenceModel
import pyLDAvis
import pyLDAvis.gensim_models as gensimvis

from bertopic import BERTopic
from sentence_transformers import SentenceTransformer
from umap import UMAP
from sklearn.cluster import KMeans

import google.generativeai as genai

warnings.filterwarnings("ignore")
os.environ["TOKENIZERS_PARALLELISM"] = "false"

# Cargar spaCy
spacy.cli.download("es_core_news_md")
nlp = spacy.load("es_core_news_md")

from google.colab import drive
drive.mount('/content/drive')

# Configuración global

RUTA_BASE       = "/content/drive/MyDrive/LetrasTXT"

GEMINI_KEYS = [
    "AIzaSyBHPHuQTYDUFNYl_YKPfGlV-DJ1olaI4Mg",
    "AIzaSyDNmuDUbejiqm5DOb4RuCkRt9aafckiwtw",
]

# Clasificación lingüística
UMBRAL_ESTANDAR = 5.0    # OOV < 5%  → ESPAÑOL_ESTANDAR
UMBRAL_REGIONAL = 18.0   # OOV < 20% → ESPAÑOL_REGIONAL
                          # OOV ≥ 20% → LENGUA_INDIGENA

# Topic modeling
RANGO_K              = range(4, 15)   # búsqueda k=4 a 14
NUM_TOPICS_ALBUM     = 3              # tópicos por álbum
SENTENCE_MODEL_NAME  = "paraphrase-multilingual-mpnet-base-v2"
N_RUNS_ESTABILIDAD   = 5              # runs para medir estabilidad

# Palabras de corte
PALABRAS_CORTE = ["Dura:", "Tema:", "Personajes:"]

# Stopwords adicionales: muletillas y rellenos líricos
STOPWORDS_EXTRA = {
    "pa","na","eh","ah","oh","uh","ooh","aah","mmm","mm",
    "hmm","hey","ha","ja","jaja","oe","ay","ey","ya","pue",
    "pos","wey","wei","bro","tamo","ta","toy","ora","pues",
    "eeh","uff","uhh","ahh","ohh","yeh","yeah","aha","aja",
    "dale","bueh","lah","deh","bah","tra",
    "rum","bum","tan","ran","din","don","tro","pom","cro","ach","bom",
}

# Paleta de colores por álbum
PALETTE = [
    "#3498db","#e74c3c","#2ecc71","#9b59b6","#f39c12",
    "#1abc9c","#e67e22","#e91e63","#00bcd4","#8bc34a",
    "#ff5722","#607d8b","#795548","#009688",
]

def color_album(nombre):
    idx = int(hashlib.md5(nombre.encode()).hexdigest(), 16) % len(PALETTE)
    return PALETTE[idx]

# Configurar Gemini
genai.configure(api_key=GEMINI_KEYS[0])
gemini_model = genai.GenerativeModel("gemini-2.5-flash-lite")

# Metadata de álbumes

METADATA_ALBUMES = [
    {"album": "A VIAJAR SE HA DICHO",                    "año": 2010},
    {"album": "CANTACUENTOS",                             "año": 1999},
    {"album": "CORRE TRENECITO",                          "año": 1998},
    {"album": "EL DUENDE DE LOS CAMINOS",                 "año": 1999},
    {"album": "EL RINCÓN DE LOS NIÑOS VOL. 2",            "año": 1978},
    {"album": "EL RINCÓN DE LOS NIÑOS VOL. 3",            "año": 1979},
    {"album": "EL RINCÓN DE LOS NIÑOS VOL. 6",            "año": 1982}, #Duda
    {"album": "EL RINCÓN DE LOS NIÑOS VOL.4",             "año": 1980}, #Duda
    {"album": "HUACHITO",                                  "año": 2000},
    {"album": "LOS RINCÓN Y DON PULPO",                   "año": 1991},
    {"album": "SON DE LA CIUDAD",                          "año": 1995}, # No tengo
    {"album": "TODO CABE EN UN JUEGO SI LO SABES ACOMODAR","año": 1986},
    {"album": "UATSI SAPICHU",                             "año": 2000},
    {"album": "UN MAULLIDO EN LA AZOTEA",                  "año": 1992},
]

metadata_df = pd.DataFrame(METADATA_ALBUMES)
print(f"Metadata cargada: {len(metadata_df)} álbumes")
print(metadata_df.to_string(index=False))

# ── Funciones de carga ────────────────────────────────────────
  RE_AUTOR      = re.compile(r'^autor\s*[:\.]?\s*', re.IGNORECASE)
  RE_PARENTESIS = re.compile(r'\(.*?\)', re.DOTALL)

  def limpiar_parentesis(texto):
      def reemplazar(match):
          return match.group(0) if len(match.group(0)) <= 6 else ""
      return RE_PARENTESIS.sub(reemplazar, texto)

  def procesar_archivo_raw(texto_raw, nombre_cancion):
      lineas     = texto_raw.split("\n")
      autor      = None
      idx_inicio = 0

      # Paso 1 — eliminar línea del título
      for i, linea in enumerate(lineas):
          if linea.strip().lower() == nombre_cancion.strip().lower():
              idx_inicio = i + 1
              break

      # Paso 2 — saltar líneas vacías después del título
      while idx_inicio < len(lineas) and not lineas[idx_inicio].strip():
          idx_inicio += 1

      # Paso 3 — revisar si la siguiente línea no vacía es autor
      if idx_inicio < len(lineas) and RE_AUTOR.match(lineas[idx_inicio].strip()):
          autor      = RE_AUTOR.sub("", lineas[idx_inicio]).strip().rstrip(".")
          idx_inicio += 1
          # Saltar líneas vacías después del autor
          while idx_inicio < len(lineas) and not lineas[idx_inicio].strip():
              idx_inicio += 1

      texto_letra = "\n".join(lineas[idx_inicio:])
      texto_letra = limpiar_parentesis(texto_letra)
      return autor, texto_letra

# ── Carga del corpus crudo ────────────────────────────────────

def cortar_metadata(texto):
    """Elimina metadata del archivo (Dura:, Tema:, Personajes:)."""
    for marca in PALABRAS_CORTE:
        if marca in texto:
            texto = texto.split(marca)[0]
    return re.sub(r"\s+", " ", texto.strip())

registros = []
registros_meta = []

for album in sorted(os.listdir(RUTA_BASE)):
    ruta_album = os.path.join(RUTA_BASE, album)
    if not os.path.isdir(ruta_album):
        continue
    for archivo in sorted(os.listdir(ruta_album)):
        if not archivo.endswith(".txt"):
            continue
        cancion = archivo.replace(".txt", "")
        with open(os.path.join(ruta_album, archivo), "r", encoding="utf-8") as f:
            texto_raw = f.read()

        autor, texto_sin_encabezado = procesar_archivo_raw(texto_raw, cancion)
        texto_limpio = cortar_metadata(texto_sin_encabezado)

        registros.append({
            "album":       album,
            "cancion":     cancion,
            "id":          album + " ||| " + cancion,
            "texto_crudo": texto_limpio,
        })

corpus_df = pd.DataFrame(registros)

# Merge con metadata
corpus_df = corpus_df.merge(metadata_df, on="album", how="left")

# Tokens crudos (solo split por espacios, sin limpiar)
corpus_df["n_tokens_crudos"] = corpus_df["texto_crudo"].apply(
    lambda t: len(t.split())
)

print(f"Corpus cargado")
print(f"  Álbumes   : {corpus_df['album'].nunique()}")
print(f"  Canciones : {len(corpus_df)}")
print(f"  IDs únicos: {corpus_df['id'].nunique()}")
print(f"  Tokens crudos totales: {corpus_df['n_tokens_crudos'].sum():,}")

corpus_df.head(10)

# ── 2.1 Estadísticas generales ────────────────────────────────
print("══ ESTADÍSTICAS GENERALES ══\n")
print(f"  Total álbumes         : {corpus_df['album'].nunique()}")
print(f"  Total canciones       : {len(corpus_df)}")
print(f"  Canciones únicas      : {corpus_df['cancion'].nunique()}")
print(f"  Tokens crudos totales : {corpus_df['n_tokens_crudos'].sum():,}")
print(f"  Promedio tokens/canción: {corpus_df['n_tokens_crudos'].mean():.1f}")
print(f"  Mediana tokens/canción : {corpus_df['n_tokens_crudos'].median():.1f}")
print(f"  Mínimo tokens          : {corpus_df['n_tokens_crudos'].min()}")
print(f"  Máximo tokens          : {corpus_df['n_tokens_crudos'].max()}")

print("\n── Canciones por álbum ───────────────────────────────")
por_album = (corpus_df.groupby("album")
             .agg(n_canciones=("cancion","count"),
                  n_tokens=("n_tokens_crudos","sum"),
                  minimo_tokens=("n_tokens_crudos","min"),
                  promedio_tokens=("n_tokens_crudos","mean"),
                  año=("año","first"))
             .round(1)
             .sort_values("año")
             .reset_index())
print(por_album.to_string(index=False))

corpus_df[corpus_df["n_tokens_crudos"] < 40]

a = corpus_df[corpus_df["cancion"] == "EL GALLITO"]

texto = a["texto_crudo"].iloc[0]
print(texto)

# ── 2.2 Canciones duplicadas entre álbumes ────────────────────
print("══ CANCIONES DUPLICADAS ENTRE ÁLBUMES ══\n")
dup = (corpus_df.groupby("cancion")["album"]
       .nunique()
       .reset_index(name="n_albumes")
       .query("n_albumes > 1")
       .sort_values("n_albumes", ascending=False))

if len(dup) > 0:
    print(f"  {len(dup)} canciones aparecen en más de un álbum:\n")
    for _, row in dup.iterrows():
        albumes = corpus_df[corpus_df["cancion"]==row["cancion"]]["album"].tolist()
        print(f"  '{row['cancion']}' → {albumes}")
else:
    print("  No hay canciones duplicadas entre álbumes")

# ── 2.3 Distribución de longitud (histograma) ─────────────────
fig = px.histogram(
    corpus_df, x="n_tokens_crudos",
    nbins=40,
    title="Distribución de longitud de canciones (tokens crudos)",
    labels={"n_tokens_crudos":"Tokens por canción","count":"Canciones"},
    color_discrete_sequence=["#3498db"]
)
fig.add_vline(x=corpus_df["n_tokens_crudos"].mean(),
              line_dash="dash", line_color="red",
              annotation_text=f"Media: {corpus_df['n_tokens_crudos'].mean():.0f}")
#fig.add_vline(x=corpus_df["n_tokens_crudos"].median(),
 #             line_dash="dot", line_color="green",
  #            annotation_text=f"Mediana: {corpus_df['n_tokens_crudos'].median():.0f}",annotation_yshift=-13)
fig.update_traces(marker_line_color="black",marker_line_width=.6)

fig.update_layout(plot_bgcolor="white", paper_bgcolor="white")
fig.show()

# ── 2.4 Top 30 palabras crudas (incluye stopwords) ────────────
palabras_crudas = []
for texto in corpus_df["texto_crudo"]:
    palabras_crudas.extend(texto.lower().split())

freq_cruda = pd.DataFrame(
    Counter(palabras_crudas).most_common(30),
    columns=["word","n"]
)
fig = px.bar(freq_cruda.sort_values("n"),
             x="n", y="word", orientation="h",
             title="Top 30 palabras — corpus crudo (incluye stopwords)",
             color="n", color_continuous_scale="blues")
fig.update_layout(plot_bgcolor="white", paper_bgcolor="white",
                  yaxis=dict(categoryorder="total ascending"),
                  height=600)
fig.show()

# ── 2.5 Línea temporal de álbumes ─────────────────────────────
fig = px.scatter(
    por_album,
    x="año", y="n_canciones",
    size="n_tokens",
    text="album",
    title="Corpus en el tiempo — álbumes por año de publicación",
    labels={"año":"Año de publicación","n_canciones":"Canciones en el álbum"},
    color="n_tokens", color_continuous_scale="viridis"
)
fig.update_traces(textposition="top center", textfont_size=9)
fig.update_layout(plot_bgcolor="white", paper_bgcolor="white",
                  xaxis=dict(dtick=2))
fig.show()

# ── Pipeline de preprocesamiento ─────────────────────────────

def preprocesar(texto):
    """
    Lematiza tokens conocidos por spaCy.
    Preserva OOV con texto original (purépecha, regionalismos, onomatopeyas).
    """
    doc = nlp(texto.lower())
    tokens = []
    for token in doc:
        if (token.is_alpha
                and len(token) > 2
                and not token.is_stop
                and token.lemma_ not in STOPWORDS_EXTRA
                and token.text  not in STOPWORDS_EXTRA):
            if token.is_oov:
                tokens.append(token.text)    # OOV → texto original
            else:
                tokens.append(token.lemma_)  # conocido → lema
    return tokens

print("Preprocesando corpus...")
corpus_df["tokens"]   = corpus_df["texto_crudo"].apply(preprocesar)
corpus_df["n_tokens"] = corpus_df["tokens"].apply(len)

tokens_df = (corpus_df
             .explode("tokens")
             .rename(columns={"tokens":"word"})
             [["album","cancion","id","año","word"]]
             .dropna(subset=["word"])
             .query("word.str.len() > 2")
             .reset_index(drop=True))

print(f"Preprocesamiento completado")
print(f"  Tokens post-procesamiento : {len(tokens_df):,}")
print(f"  Vocabulario único         : {tokens_df['word'].nunique():,}")

# ── 4.1 Comparativa antes/después ────────────────────────────
print("══ COMPARATIVA ANTES / DESPUÉS DEL PROCESAMIENTO ══\n")

comparativa = (corpus_df.groupby("album")
               .agg(tokens_crudos=("n_tokens_crudos","sum"),
                    tokens_limpios=("n_tokens","sum"),
                    año=("año","first"))
               .reset_index()
               .sort_values("año"))
comparativa["reduccion_pct"] = round(
    100 * (1 - comparativa["tokens_limpios"] / comparativa["tokens_crudos"]), 1
)
print(comparativa[["album","tokens_crudos","tokens_limpios","reduccion_pct"]]
      .to_string(index=False))

total_crudos  = comparativa["tokens_crudos"].sum()
total_limpios = comparativa["tokens_limpios"].sum()
print(f"\n  TOTAL crudos  : {total_crudos:,}")
print(f"  TOTAL limpios : {total_limpios:,}")
print(f"  Reducción     : {100*(1-total_limpios/total_crudos):.1f}%")
print(f"  Vocabulario único (limpio): {tokens_df['word'].nunique():,}")

# ── 4.2 Vocabulario eliminado — desglose por categoría ────────
print("══ VOCABULARIO ELIMINADO POR CATEGORÍA ══\n")

palabras_orig    = set()
eliminadas_stop  = set()
eliminadas_extra = set()
eliminadas_cortas= set()
eliminadas_nalfa = set()

for texto in corpus_df["texto_crudo"]:
    doc = nlp(texto.lower())
    for token in doc:
        palabras_orig.add(token.text)
        if not token.is_alpha:
            eliminadas_nalfa.add(token.text)
        elif len(token) <= 2:
            eliminadas_cortas.add(token.text)
        elif token.is_stop:
            eliminadas_stop.add(token.text)
        elif token.lemma_ in STOPWORDS_EXTRA or token.text in STOPWORDS_EXTRA:
            eliminadas_extra.add(token.text)

palabras_finales  = set(tokens_df["word"].unique())
no_clasificadas   = palabras_orig - palabras_finales - eliminadas_nalfa - eliminadas_cortas - eliminadas_stop - eliminadas_extra

print(f"  Palabras únicas originales    : {len(palabras_orig):,}")
print(f"  Palabras únicas post-procesamiento : {len(palabras_finales):,}")
print(f"\n  Desglose de eliminadas:")
print(f"    No alfabéticas (núm, puntuación)  : {len(eliminadas_nalfa):,}")
print(f"    Muy cortas (≤2 caracteres)         : {len(eliminadas_cortas):,}")
print(f"    Stopwords spaCy                    : {len(eliminadas_stop):,}")
print(f"    Stopwords extra (muletillas)       : {len(eliminadas_extra):,}")
print(f"\n  Stopwords spaCy eliminadas (muestra):")
print(f"    {sorted(list(eliminadas_stop))}")
print(f"\n  Stopwords extra eliminadas:")
print(f"    {sorted(eliminadas_extra)}")
print(f"\n  Tokens cortos eliminados (muestra):")
print(f"    {sorted(list(eliminadas_cortas))}")

# ── 4.3 Palabras OOV — vocabulario no reconocido por spaCy ────
# Estas son candidatas a purépecha, regionalismos u onomatopeyas
print("══ PALABRAS OOV (fuera del vocabulario spaCy) ══\n")
print("  Estas palabras se PRESERVARON en el corpus final.\n")

registros_oov = []
for _, row in corpus_df.iterrows():
    doc = nlp(row["texto_crudo"].lower())
    for token in doc:
        if (token.is_alpha and len(token) > 2
                and not token.is_stop
                and token.text not in STOPWORDS_EXTRA
                and token.is_oov):
            registros_oov.append({
                "album":   row["album"],
                "cancion": row["cancion"],
                "word":    token.text,
            })

oov_df = pd.DataFrame(registros_oov)

print(f"  Total tokens OOV preservados : {len(oov_df):,}")
print(f"  Vocabulario OOV único        : {oov_df['word'].nunique():,}")
print(f"\n  Top 30 palabras OOV del corpus:")
print(oov_df["word"].value_counts().head(30).reset_index()
      .rename(columns={"index":"word","count":"n"})
      .to_string(index=False))

print(f"\n  OOV por álbum (% sobre tokens limpios):")
oov_album = (oov_df.groupby("album")["word"].count()
             .reset_index(name="n_oov")
             .merge(corpus_df.groupby("album")["n_tokens"].sum()
                    .reset_index(name="n_total"), on="album"))
oov_album["pct_oov"] = round(100 * oov_album["n_oov"] / oov_album["n_total"], 1)
print(oov_album.sort_values("pct_oov", ascending=False).to_string(index=False))

# ── 4.4 Top palabras post-procesamiento ───────────────────────
top_post = tokens_df["word"].value_counts().head(30).reset_index()
top_post.columns = ["word","n"]

fig = px.bar(top_post.sort_values("n"),
             x="n", y="word", orientation="h",
             title="Top 30 palabras — corpus post-procesamiento",
             color="n", color_continuous_scale="viridis")
fig.update_layout(plot_bgcolor="white", paper_bgcolor="white",
                  yaxis=dict(categoryorder="total ascending"), height=600)
fig.show()

# ── 4.5 Wordcloud global ──────────────────────────────────────
freq_global = dict(tokens_df["word"].value_counts())
wc = WordCloud(width=1200, height=500, background_color="white",
               colormap="viridis", max_words=100)
wc.generate_from_frequencies(freq_global)
plt.figure(figsize=(16, 6))
plt.imshow(wc, interpolation="bilinear")
plt.axis("off")
plt.title("Nube de palabras — corpus global post-procesamiento",
          fontsize=14, fontweight="bold")
plt.tight_layout()
plt.show()

# ── Clasificación por álbum ───────────────────────────────────

def asignar_categoria(pct_oov):
    if pct_oov < UMBRAL_ESTANDAR:
        return "ESPAÑOL_ESTANDAR"
    elif pct_oov < UMBRAL_REGIONAL:
        return "ESPAÑOL_REGIONAL"
    else:
        return "LENGUA_INDIGENA"

clasificacion = (oov_album[["album","pct_oov"]]
                 .copy()
                 .rename(columns={"pct_oov":"pct_oov_album"}))
clasificacion["categoria"] = clasificacion["pct_oov_album"].apply(asignar_categoria)

# Merge a corpus_df y tokens_df
if "categoria" in corpus_df.columns:
    corpus_df = corpus_df.drop(columns=["categoria"])
corpus_df = corpus_df.merge(clasificacion[["album","categoria"]], on="album", how="left")
tokens_df = tokens_df.merge(clasificacion[["album","categoria"]], on="album", how="left")

# ── Resultados ────────────────────────────────────────────────
print("══ CLASIFICACIÓN LINGÜÍSTICA ══\n")
print(f"  Umbrales:")
print(f"    OOV < {UMBRAL_ESTANDAR}%    → ESPAÑOL_ESTANDAR")
print(f"    {UMBRAL_ESTANDAR}% ≤ OOV < {UMBRAL_REGIONAL}% → ESPAÑOL_REGIONAL")
print(f"    OOV ≥ {UMBRAL_REGIONAL}%   → LENGUA_INDIGENA\n")

tabla_cat = (clasificacion
             .merge(metadata_df, on="album")
             .sort_values("pct_oov_album", ascending=False))
print(tabla_cat[["album","año","pct_oov_album","categoria"]].to_string(index=False))

print("\n── Totales ───────────────────────────────────────────")
print(clasificacion["categoria"].value_counts().reset_index()
      .rename(columns={"index":"categoria","count":"n_albumes"})
      .to_string(index=False))

# ── Gráfica de clasificación ──────────────────────────────────
fig = px.scatter(
    tabla_cat,
    x="pct_oov_album", y="album",
    color="categoria",
    size="pct_oov_album",
    title="Clasificación lingüística por álbum (% tokens OOV)",
    labels={"pct_oov_album":"% Tokens OOV","album":"Álbum"},
    color_discrete_map={
        "LENGUA_INDIGENA":  "#9b59b6",
        "ESPAÑOL_REGIONAL": "#3498db",
        "ESPAÑOL_ESTANDAR": "#2ecc71"
    }
)
fig.add_vline(x=UMBRAL_ESTANDAR,  line_dash="dash", line_color="#2ecc71",
              annotation_text=f"ESTANDAR ({UMBRAL_ESTANDAR}%)")
fig.add_vline(x=UMBRAL_REGIONAL, line_dash="dash", line_color="#9b59b6",
              annotation_text=f"INDIGENA ({UMBRAL_REGIONAL}%)")
fig.update_layout(plot_bgcolor="white", paper_bgcolor="white", height=500)
fig.show()

# ── Utilidades compartidas ────────────────────────────────────

def preparar_lda(tokens_df_in):
    docs = tokens_df_in.groupby("id")["word"].apply(list).tolist()
    docs = [d for d in docs if len(d) >= 3]
    dictionary = Dictionary(docs)
    dictionary.filter_extremes(no_below=2, no_above=0.95)  # no_below=2
    bow = [dictionary.doc2bow(d) for d in docs]
    bow = [b for b in bow if b]
    return docs, dictionary, bow

def preparar_nmf(tokens_df_in, min_df=2):
    docs_text = (tokens_df_in.groupby("id")["word"]
                 .apply(lambda x: " ".join(x)).tolist())
    docs_text = [d for d in docs_text if len(d.split()) >= 3]
    vec = TfidfVectorizer(max_df=0.95, min_df=min_df,
                          max_features=800)  # max_features=1000
    mat = vec.fit_transform(docs_text)
    return docs_text, vec, mat

def coh_lda(lda, docs, dictionary):
    try:
        return CoherenceModel(model=lda, texts=docs,
                              dictionary=dictionary,
                              coherence="c_v").get_coherence()
    except:
        return float("nan")

def coh_nmf(H, feature_names, tfidf_mat, n=10):
    scores = []
    for vec in H:
        idx   = vec.argsort()[:-n-1:-1]
        valid = [i for i in idx if i < tfidf_mat.shape[1]]
        if len(valid) < 2: continue
        vecs = tfidf_mat[:, valid].toarray().T
        sim  = cosine_similarity(vecs)
        np.fill_diagonal(sim, 0)
        scores.append(float(sim.mean()))
    return float(np.mean(scores)) if scores else float("nan")

def diversidad_topicos(topics_words, n=10):
    todas = []
    for words in topics_words:
        todas.extend(words[:n])
    return round(len(set(todas)) / len(todas), 3) if todas else 0.0

print("Utilidades definidas")

# ── FASE 1: Búsqueda automática de k óptimo ──────────────────
print("══ FASE 1 — Búsqueda de k óptimo ══\n")

docs_g, dict_g, bow_g = preparar_lda(tokens_df)
_, vec_g, tfidf_g     = preparar_nmf(tokens_df)

res_busqueda = []

for k in RANGO_K:
    # LDA
    lda_k = LdaModel(corpus=bow_g, id2word=dict_g, num_topics=k,
                     passes=15, iterations=300, alpha="auto", eta="auto",
                     random_state=42)
    coh_l = coh_lda(lda_k, docs_g, dict_g)

    # NMF
    nmf_k = NMF(n_components=k, random_state=42, max_iter=500, init="nndsvda")
    W_k   = nmf_k.fit_transform(tfidf_g)
    H_k   = nmf_k.components_
    fn_k  = vec_g.get_feature_names_out()
    coh_n = coh_nmf(H_k, fn_k, tfidf_g)

    # Diversidad LDA
    lda_words = [[w for w,_ in lda_k.show_topic(t, 10)] for t in range(k)]
    div_l = diversidad_topicos(lda_words)

    # Diversidad NMF
    nmf_words = [[fn_k[i] for i in H_k[t].argsort()[:-11:-1]] for t in range(k)]
    div_n = diversidad_topicos(nmf_words)

    res_busqueda.append({
        "k":k, "lda_cv":coh_l, "nmf_cv_aprox":coh_n,
        "lda_diversidad":div_l, "nmf_diversidad":div_n
    })
    print(f"  k={k:2d} | LDA Cv={coh_l:.4f} div={div_l:.3f} | NMF Cv_aprox={coh_n:.4f} div={div_n:.3f}")

df_busqueda = pd.DataFrame(res_busqueda)
k_lda_opt = int(df_busqueda.loc[df_busqueda["lda_cv"].idxmax(), "k"])
k_nmf_opt = int(df_busqueda.loc[df_busqueda["nmf_cv_aprox"].idxmax(), "k"])
print(f"\n  ✓ LDA óptimo : k={k_lda_opt}")
print(f"  ✓ NMF óptimo : k={k_nmf_opt}")

# ── Búsqueda k óptimo BERTopic — Silhouette ──────────────────
print("\nBERTopic — probando k=4 a 14 (silhouette)...")
from sklearn.metrics import silhouette_score

embed_model_busq = SentenceTransformer(SENTENCE_MODEL_NAME)
textos_busq      = (tokens_df.groupby("id")["word"]
                    .apply(lambda x: " ".join(x)).tolist())
embeddings_busq  = embed_model_busq.encode(textos_busq, show_progress_bar=False)

umap_busq = UMAP(n_neighbors=15, n_components=10, min_dist=0.0,
                  metric="cosine", random_state=42)
emb_red   = umap_busq.fit_transform(embeddings_busq)

res_bert_busq = []
for k in RANGO_K:
    km  = KMeans(n_clusters=k, random_state=42, n_init=10)
    lbl = km.fit_predict(emb_red)
    sil = silhouette_score(emb_red, lbl)
    res_bert_busq.append({"k":k, "silhouette":round(sil,4)})
    print(f"  k={k:2d} → silhouette={sil:.4f}")

df_bert_busq = pd.DataFrame(res_bert_busq)
k_bert_opt   = int(df_bert_busq.loc[df_bert_busq["silhouette"].idxmax(),"k"])
print(f"\n  ✓ BERTopic óptimo: k={k_bert_opt}")

# Agregar a la gráfica de búsqueda (celda 26 la leerá)
df_busqueda["bert_silhouette"] = df_bert_busq["silhouette"].values

# ── Gráfica de búsqueda de k ──────────────────────────────────
fig = make_subplots(rows=1, cols=2,
                    subplot_titles=["Coherencia Cv vs k", "Diversidad vs k"])

fig.add_trace(go.Scatter(x=df_busqueda["k"], y=df_busqueda["lda_cv"],
                          name="LDA Cv", line=dict(color="#3498db")), row=1, col=1)
fig.add_trace(go.Scatter(x=df_busqueda["k"], y=df_busqueda["nmf_cv_aprox"],
                          name="NMF Cv_aprox", line=dict(color="#e67e22",dash="dash")), row=1, col=1)
fig.add_trace(go.Scatter(x=df_busqueda["k"], y=df_busqueda["lda_diversidad"],
                          name="LDA diversidad", line=dict(color="#3498db")), row=1, col=2)
fig.add_trace(go.Scatter(x=df_busqueda["k"], y=df_busqueda["nmf_diversidad"],
                          name="NMF diversidad", line=dict(color="#e67e22",dash="dash")), row=1, col=2)

fig.add_vline(x=k_lda_opt, line_dash="dot", line_color="#3498db", row=1, col=1)
fig.add_vline(x=k_nmf_opt, line_dash="dot", line_color="#e67e22", row=1, col=1)
fig.update_layout(title="Búsqueda de k óptimo — LDA y NMF",
                  plot_bgcolor="white", paper_bgcolor="white", height=400)
fig.show()

# Gráfica silhouette BERTopic
fig_bert_k = px.line(
    df_bert_busq, x="k", y="silhouette",
    title="BERTopic — Silhouette Score vs k",
    markers=True, color_discrete_sequence=["#9b59b6"]
)
fig_bert_k.add_vline(x=k_bert_opt, line_dash="dot", line_color="#9b59b6",
                     annotation_text=f"k={k_bert_opt}")
fig_bert_k.update_layout(plot_bgcolor="white", paper_bgcolor="white")
fig_bert_k.show()

# ── FASE 2: Modelos globales finales ─────────────────────────
print("══ FASE 2 — Modelos globales finales ══\n")

# LDA global
print(f"Entrenando LDA global (k={k_lda_opt})...")
lda_global = LdaModel(corpus=bow_g, id2word=dict_g, num_topics=k_lda_opt,
                      passes=25, iterations=500, alpha="auto", eta="auto",
                      random_state=42)
coh_lda_final = coh_lda(lda_global, docs_g, dict_g)
palabras_lda  = {t+1: [w for w,_ in lda_global.show_topic(t, 10)]
                 for t in range(k_lda_opt)}
div_lda_final = diversidad_topicos(list(palabras_lda.values()))
print(f"  LDA | Cv={coh_lda_final:.4f} | Diversidad={div_lda_final:.3f}")

# NMF global
print(f"\nEntrenando NMF global (k={k_nmf_opt})...")
nmf_global = NMF(n_components=k_nmf_opt, random_state=42,
                 max_iter=500, init="nndsvda")
W_global   = nmf_global.fit_transform(tfidf_g)
H_global   = nmf_global.components_
fn_global  = vec_g.get_feature_names_out()
coh_nmf_final = coh_nmf(H_global, fn_global, tfidf_g)
palabras_nmf  = {t+1: [fn_global[i] for i in H_global[t].argsort()[:-11:-1]]
                 for t in range(k_nmf_opt)}
div_nmf_final = diversidad_topicos(list(palabras_nmf.values()))
print(f"  NMF | Cv_aprox={coh_nmf_final:.4f} | Diversidad={div_nmf_final:.3f}")

# BERTopic global
print(f"\nEntrenando BERTopic global (k={k_lda_opt})...")
embed_model  = SentenceTransformer(SENTENCE_MODEL_NAME)
umap_model   = UMAP(n_neighbors=15, n_components=10, min_dist=0.0,
                     metric="cosine", random_state=42)
kmeans_model = KMeans(n_clusters=k_bert_opt, random_state=42, n_init=10)
bertopic_global = BERTopic(
    embedding_model=embed_model,
    umap_model=umap_model,
    hdbscan_model=kmeans_model,
    language="multilingual",
    calculate_probabilities=False,
    verbose=False,
    nr_topics=k_bert_opt,
)
textos_bert = (tokens_df.groupby("id")["word"]
               .apply(lambda x: " ".join(x)))
ids_bert    = textos_bert.index.tolist()
topics_bert, _ = bertopic_global.fit_transform(textos_bert.tolist())
n_outliers = sum(1 for t in topics_bert if t == -1)
palabras_bert = {}
for tid in set(topics_bert):
    if tid == -1: continue
    try:
        words = bertopic_global.get_topic(tid)
        palabras_bert[tid] = [w for w,_ in words[:10]]
    except: pass
div_bert_final = diversidad_topicos(list(palabras_bert.values()))
print(f"  BERTopic | Tópicos={len(palabras_bert)} | Outliers={n_outliers} | Diversidad={div_bert_final:.3f}")

# ── FASE 3: Asignación global a corpus_df ────────────────────
print("══ FASE 3 — Asignación global ══\n")

# LDA
filas_lda = []
for id_c, group in tokens_df.groupby("id"):
    bow = dict_g.doc2bow(group["word"].tolist())
    if not bow: continue
    dist = lda_global.get_document_topics(bow)
    top  = max(dist, key=lambda x: x[1])
    filas_lda.append({"id":id_c,"topico_lda_global":top[0]+1,
                      "prob_lda_global":round(top[1],3)})
df_lda_asig = pd.DataFrame(filas_lda)

# NMF
docs_nmf  = tokens_df.groupby("id")["word"].apply(lambda x: " ".join(x))
tfidf_pred= vec_g.transform(docs_nmf)
W_pred    = nmf_global.transform(tfidf_pred)
df_nmf_asig = pd.DataFrame({
    "id":                docs_nmf.index,
    "topico_nmf_global": (np.argmax(W_pred, axis=1)+1).tolist()
})

# BERTopic
df_bert_asig = pd.DataFrame({
    "id":                 ids_bert,
    "topico_bert_global": topics_bert
})

# Merge
for col in ["topico_lda_global","prob_lda_global",
            "topico_nmf_global","topico_bert_global"]:
    if col in corpus_df.columns:
        corpus_df = corpus_df.drop(columns=[col])

corpus_df = (corpus_df
             .merge(df_lda_asig,  on="id", how="left")
             .merge(df_nmf_asig,  on="id", how="left")
             .merge(df_bert_asig, on="id", how="left"))

print(f"Tópicos globales asignados a {len(corpus_df)} canciones")
print("\n── Tópicos LDA global ─────────────────────────────────")
for tid, words in palabras_lda.items():
    print(f"  T{tid:2d}: {' | '.join(words)}")
print("\n── Tópicos NMF global ─────────────────────────────────")
for tid, words in palabras_nmf.items():
    print(f"  T{tid:2d}: {' | '.join(words)}")
print("\n── Tópicos BERTopic global ────────────────────────────")
for tid, words in sorted(palabras_bert.items()):
    print(f"  T{tid:2d}: {' | '.join(words)}")

# ── Etiquetado con Gemini — batch completo ───────────────────

def llamar_gemini_con_rotacion(prompt):
    """Intenta cada API key en orden. Si todas fallan, espera y reintenta."""
    for key in GEMINI_KEYS:
        genai.configure(api_key=key)
        model_tmp = genai.GenerativeModel("gemini-2.5-flash-lite")
        for intento in range(3):
            try:
                response = model_tmp.generate_content(prompt)
                time.sleep(4)
                return response.text
            except Exception as e:
                if "429" in str(e):
                    match  = re.search(r'retry in ([\d\.]+)s', str(e))
                    espera = float(match.group(1)) + 3 if match else 65
                    print(f"  Key agotada, esperando {espera:.0f}s...")
                    time.sleep(espera)
                    break
                return f"Error: {e}"
    return "Sin etiquetar"

def etiquetar_modelo_completo(palabras_por_topico, nombre_modelo):
    """
    Envía TODOS los tópicos de un modelo en un solo prompt.
    Devuelve diccionario {topico_id: etiqueta}.
    """
    lineas = "\n".join([
        f"  T{tid}: {' | '.join(words)}"
        for tid, words in palabras_por_topico.items()
    ])

    prompt = f"""Eres un experto en música infantil latinoamericana (México, 1969-2010).

Estos son los tópicos obtenidos por {nombre_modelo} del análisis de letras de canciones infantiles:

{lineas}

Para cada tópico asigna una etiqueta temática en español (máximo 5 palabras).
El corpus es música infantil: animales, juegos, naturaleza, familia, lengua indígena, onomatopeyas, etc.

Responde ÚNICAMENTE en este formato, sin explicaciones adicionales:
T1: etiqueta
T2: etiqueta
T3: etiqueta
... (un tópico por línea)"""

    texto = llamar_gemini_con_rotacion(prompt)
    etiquetas = {}
    for linea in texto.strip().split("\n"):
        linea = linea.strip()
        if not linea: continue
        match = re.match(r'T(\d+)\s*:\s*(.+)', linea)
        if match:
            etiquetas[int(match.group(1))] = match.group(2).strip().strip(".")
    return etiquetas

# ── Etiquetar los 3 modelos ───────────────────────────────────
print("Etiquetando tópicos con Gemini...\n")

print("── LDA ──────────────────────────────────────────────")
etiquetas_lda = etiquetar_modelo_completo(palabras_lda, "LDA")

print("── NMF ──────────────────────────────────────────────")
etiquetas_nmf = etiquetar_modelo_completo(palabras_nmf, "NMF")

print("── BERTopic ─────────────────────────────────────────")
palabras_bert_idx1 = {tid+1: words for tid, words in palabras_bert.items()}
etiquetas_bert_tmp = etiquetar_modelo_completo(palabras_bert_idx1, "BERTopic")
etiquetas_bert     = {tid-1: etiq for tid, etiq in etiquetas_bert_tmp.items()}

# Agregar etiquetas a corpus_df
corpus_df["etiqueta_lda"]  = corpus_df["topico_lda_global"].map(etiquetas_lda)
corpus_df["etiqueta_nmf"]  = corpus_df["topico_nmf_global"].map(etiquetas_nmf)
corpus_df["etiqueta_bert"] = corpus_df["topico_bert_global"].map(etiquetas_bert)

# ── Mostrar resultados ────────────────────────────────────────
print("\n── Etiquetas LDA ────────────────────────────────────")
for tid, words in palabras_lda.items():
    print(f"  T{tid:2d}: [{etiquetas_lda.get(tid,'—')}]")
    print(f"       {' | '.join(words[:6])}")

print("\n── Etiquetas NMF ────────────────────────────────────")
for tid, words in palabras_nmf.items():
    print(f"  T{tid:2d}: [{etiquetas_nmf.get(tid,'—')}]")
    print(f"       {' | '.join(words[:6])}")

print("\n── Etiquetas BERTopic ───────────────────────────────")
for tid, words in sorted(palabras_bert.items()):
    print(f"  T{tid:2d}: [{etiquetas_bert.get(tid,'—')}]")
    print(f"       {' | '.join(words[:6])}")

# ── Estabilidad — múltiples runs ─────────────────────────────
print(f"Calculando estabilidad ({N_RUNS_ESTABILIDAD} runs por modelo)...\n")

def estabilidad_lda(n_runs=5):
    tops_runs = []
    for seed in range(n_runs):
        lda_r = LdaModel(corpus=bow_g, id2word=dict_g,
                          num_topics=k_lda_opt, passes=15, iterations=200,
                          alpha="auto", eta="auto", random_state=seed)
        top_words = frozenset(
            w for t in range(k_lda_opt)
            for w, _ in lda_r.show_topic(t, 10)
        )
        tops_runs.append(top_words)
    # Jaccard promedio entre todos los pares de runs
    pares = [(i,j) for i in range(n_runs) for j in range(i+1,n_runs)]
    sims  = [len(tops_runs[i]&tops_runs[j])/len(tops_runs[i]|tops_runs[j])
             for i,j in pares]
    return round(np.mean(sims), 3)

def estabilidad_nmf(n_runs=5):
    tops_runs = []
    for seed in range(n_runs):
        nmf_r = NMF(n_components=k_nmf_opt, random_state=seed,
                    max_iter=300, init="nndsvda")
        H_r   = nmf_r.fit_transform(tfidf_g)
        H_mat = nmf_r.components_
        top_words = frozenset(
            fn_global[i]
            for t in range(k_nmf_opt)
            for i in H_mat[t].argsort()[:-11:-1]
        )
        tops_runs.append(top_words)
    pares = [(i,j) for i in range(n_runs) for j in range(i+1,n_runs)]
    sims  = [len(tops_runs[i]&tops_runs[j])/len(tops_runs[i]|tops_runs[j])
             for i,j in pares]
    return round(np.mean(sims), 3)

estab_lda = estabilidad_lda(N_RUNS_ESTABILIDAD)
estab_nmf = estabilidad_nmf(N_RUNS_ESTABILIDAD)
print(f"  LDA estabilidad : {estab_lda}")
print(f"  NMF estabilidad : {estab_nmf}")

# ── Consistencia entre modelos — ARI y NMI ───────────────────
from sklearn.metrics import adjusted_rand_score, normalized_mutual_info_score

# Obtener asignaciones numéricas por canción
lda_labels  = corpus_df["topico_lda_global"].fillna(-1).astype(int).tolist()
nmf_labels  = corpus_df["topico_nmf_global"].fillna(-1).astype(int).tolist()
bert_labels = corpus_df["topico_bert_global"].fillna(-1).astype(int).tolist()

ari_lda_nmf  = adjusted_rand_score(lda_labels, nmf_labels)
ari_lda_bert = adjusted_rand_score(lda_labels, bert_labels)
ari_nmf_bert = adjusted_rand_score(nmf_labels, bert_labels)

nmi_lda_nmf  = normalized_mutual_info_score(lda_labels, nmf_labels)
nmi_lda_bert = normalized_mutual_info_score(lda_labels, bert_labels)
nmi_nmf_bert = normalized_mutual_info_score(nmf_labels, bert_labels)

consistencia_df = pd.DataFrame([
    {"Par": "LDA vs NMF",   "ARI": round(ari_lda_nmf,4),
     "NMI": round(nmi_lda_nmf,4)},
    {"Par": "LDA vs BERTopic", "ARI": round(ari_lda_bert,4),
     "NMI": round(nmi_lda_bert,4)},
    {"Par": "NMF vs BERTopic", "ARI": round(ari_nmf_bert,4),
     "NMI": round(nmi_nmf_bert,4)},
])

print("══ CONSISTENCIA ENTRE MODELOS ══\n")
print("  ARI y NMI — rango 0 a 1, mayor = más consistente")
print("  Nota: k distintos entre modelos reduce ARI por construcción\n")
print(consistencia_df.to_string(index=False))

# Gráfica
fig_cons = px.bar(
    consistencia_df.melt(id_vars="Par", var_name="Métrica", value_name="Score"),
    x="Par", y="Score", color="Métrica", barmode="group",
    title="Consistencia entre modelos — ARI y NMI",
    color_discrete_map={"ARI":"#3498db","NMI":"#e67e22"}
)
fig_cons.update_layout(plot_bgcolor="white", paper_bgcolor="white",
                       yaxis=dict(range=[0,1]))
fig_cons.show()

# ── Tabla comparativa final ───────────────────────────────────
metricas_comparativa = pd.DataFrame([
    {
        "Modelo":       "LDA",
        "k":            k_lda_opt,
        "Coherencia":   round(coh_lda_final, 4),
        "Tipo_coh":     "Cv real",
        "Diversidad":   div_lda_final,
        "Estabilidad":  estab_lda,
        "Outliers":     "N/A",
    },
    {
        "Modelo":       "NMF",
        "k":            k_nmf_opt,
        "Coherencia":   round(coh_nmf_final, 4),
        "Tipo_coh":     "Cv_aprox",
        "Diversidad":   div_nmf_final,
        "Estabilidad":  estab_nmf,
        "Outliers":     "N/A",
    },
    {
        "Modelo":       "BERTopic",
        "k":            k_lda_opt,
        "Coherencia":   "—",
        "Tipo_coh":     "—",
        "Diversidad":   div_bert_final,
        "Estabilidad":  "—",
        "Outliers":     n_outliers,
    },
])

print("══ TABLA COMPARATIVA DE MODELOS ══\n")
print(metricas_comparativa.to_string(index=False))

# Gráfica comparativa de coherencia vs k
fig = px.bar(
    df_busqueda.melt(id_vars="k",
                     value_vars=["lda_cv","nmf_cv_aprox"],
                     var_name="modelo", value_name="coherencia"),
    x="k", y="coherencia", color="modelo", barmode="group",
    title="Coherencia vs número de tópicos (k)",
    labels={"k":"Número de tópicos","coherencia":"Coherencia"},
    color_discrete_map={"lda_cv":"#3498db","nmf_cv_aprox":"#e67e22"}
)
fig.add_vline(x=k_lda_opt, line_dash="dot", line_color="#3498db",
              annotation_text=f"k LDA={k_lda_opt}")
fig.add_vline(x=k_nmf_opt, line_dash="dot", line_color="#e67e22",
              annotation_text=f"k NMF={k_nmf_opt}")
fig.update_layout(plot_bgcolor="white", paper_bgcolor="white")
fig.show()

# ── Modelos por álbum ─────────────────────────────────────────
print(f"══ MODELOS POR ÁLBUM (k={NUM_TOPICS_ALBUM}) ══\n")
resultados_album = {}

for album in sorted(tokens_df["album"].unique()):
    tok_a = tokens_df[tokens_df["album"] == album]
    n_can = tok_a["id"].nunique()
    print(f"  {album} ({n_can} canciones)")

    res = {"album":album, "n_canciones":n_can,
           "lda":None,"lda_coh":None,"lda_palabras":None,
           "lda_dict":None,"lda_bow":None,"lda_docs":None,
           "nmf":None,"nmf_coh":None,"nmf_palabras":None,
           "nmf_vec":None}

    # LDA por álbum
    try:
        docs_a, dict_a, bow_a = preparar_lda(tok_a)
        if len(docs_a) >= NUM_TOPICS_ALBUM:
            lda_a = LdaModel(corpus=bow_a, id2word=dict_a,
                             num_topics=NUM_TOPICS_ALBUM,
                             passes=20, iterations=400,
                             alpha="auto", eta="auto", random_state=42)
            coh_a = coh_lda(lda_a, docs_a, dict_a)
            palabras_a = {t+1:[w for w,_ in lda_a.show_topic(t,8)]
                          for t in range(NUM_TOPICS_ALBUM)}
            res.update({"lda":lda_a,"lda_coh":coh_a,
                        "lda_palabras":palabras_a,
                        "lda_dict":dict_a,"lda_bow":bow_a,"lda_docs":docs_a})
            print(f"    LDA Cv={coh_a:.4f}")
    except Exception as e:
        print(f"    LDA error: {e}")

    # NMF por álbum
    try:
        _, vec_a, tfidf_a = preparar_nmf(tok_a, min_df=1)
        nmf_a = NMF(n_components=NUM_TOPICS_ALBUM, random_state=42,
                    max_iter=500, init="nndsvda")
        W_a   = nmf_a.fit_transform(tfidf_a)
        H_a   = nmf_a.components_
        fn_a  = vec_a.get_feature_names_out()
        coh_n = coh_nmf(H_a, fn_a, tfidf_a)
        palabras_n = {t+1:[fn_a[i] for i in H_a[t].argsort()[:-9:-1]]
                      for t in range(NUM_TOPICS_ALBUM)}
        res.update({"nmf":nmf_a,"nmf_coh":coh_n,
                    "nmf_palabras":palabras_n,"nmf_vec":vec_a})
        print(f"    NMF Cv_aprox={coh_n:.4f}")
    except Exception as e:
        print(f"    NMF error: {e}")

    resultados_album[album] = res

print("\nModelos por álbum completados")

# ── Asignar tópicos por álbum a corpus_df ────────────────────
filas_album = []
for album, res in resultados_album.items():
    tok_a = tokens_df[tokens_df["album"] == album]

    lda_alb = {}
    if res["lda"]:
        for id_c, group in tok_a.groupby("id"):
            bow = res["lda_dict"].doc2bow(group["word"].tolist())
            if not bow: continue
            dist = res["lda"].get_document_topics(bow)
            top  = max(dist, key=lambda x: x[1])
            lda_alb[id_c] = top[0]+1

    nmf_alb = {}
    if res["nmf"]:
        docs_c  = tok_a.groupby("id")["word"].apply(lambda x: " ".join(x))
        tfidf_c = res["nmf_vec"].transform(docs_c)
        W_c     = res["nmf"].transform(tfidf_c)
        for i, id_c in enumerate(docs_c.index):
            nmf_alb[id_c] = int(np.argmax(W_c[i])+1)

    for id_c in tok_a["id"].unique():
        filas_album.append({
            "id":               id_c,
            "topico_lda_album": lda_alb.get(id_c),
            "topico_nmf_album": nmf_alb.get(id_c)
        })

df_album_asig = pd.DataFrame(filas_album).drop_duplicates(subset=["id"])
for col in ["topico_lda_album","topico_nmf_album"]:
    if col in corpus_df.columns:
        corpus_df = corpus_df.drop(columns=[col])
corpus_df = corpus_df.merge(df_album_asig, on="id", how="left")

# ── Etiquetar tópicos por álbum — un solo prompt ─────────────
print("Etiquetando tópicos por álbum con Gemini (una consulta)...")

# Construir bloque completo con todos los álbumes y modelos
lineas_prompt = []
for album, res in resultados_album.items():
    nombre_corto = album[:30]
    if res.get("lda_palabras"):
        for tid, words in res["lda_palabras"].items():
            lineas_prompt.append(
                f"ALBUM:{nombre_corto}|LDA|T{tid}: {' | '.join(words)}"
            )
    if res.get("nmf_palabras"):
        for tid, words in res["nmf_palabras"].items():
            lineas_prompt.append(
                f"ALBUM:{nombre_corto}|NMF|T{tid}: {' | '.join(words)}"
            )

bloque_topicos = "\n".join(lineas_prompt)

prompt_album = f"""Eres un experto en música infantil latinoamericana (México, 1969-2010).

Estos son los tópicos internos de cada álbum, encontrados por análisis automático (LDA y NMF).
Cada línea tiene el formato: ALBUM:nombre|MODELO|Tnúmero: palabra1 | palabra2 | ...

{bloque_topicos}

Para cada línea asigna una etiqueta temática en español (máximo 5 palabras).
El corpus es música infantil: animales, juegos, naturaleza, familia, lengua indígena, etc.

Responde ÚNICAMENTE en este formato, una línea por tópico, sin explicaciones:
ALBUM:nombre|LDA|T1: etiqueta
ALBUM:nombre|LDA|T2: etiqueta
ALBUM:nombre|NMF|T1: etiqueta
...
"""

respuesta_raw = llamar_gemini_con_rotacion(prompt_album)

# Parsear respuesta
etiquetas_album = {}
for linea in respuesta_raw.strip().split("\n"):
    linea = linea.strip()
    if not linea: continue
    # Formato esperado: ALBUM:nombre|MODELO|Tnúm: etiqueta
    match = re.match(r'ALBUM:(.+?)\|(\w+)\|T(\d+):\s*(.+)', linea)
    if not match: continue
    nombre_corto = match.group(1).strip()
    modelo       = match.group(2).strip().lower()   # "lda" o "nmf"
    tid          = int(match.group(3))
    etiqueta     = match.group(4).strip().strip(".")

    # Encontrar el álbum completo que corresponde al nombre corto
    album_completo = next(
        (a for a in resultados_album if a[:30] == nombre_corto), None
    )
    if album_completo is None: continue

    if album_completo not in etiquetas_album:
        etiquetas_album[album_completo] = {"lda":{}, "nmf":{}}
    etiquetas_album[album_completo][modelo][tid] = etiqueta

# ── Resumen por álbum ─────────────────────────────────────────
print("\n══ TÓPICOS POR ÁLBUM ══\n")
for album, res in resultados_album.items():
    print(f"  {album}")
    if res.get("lda_palabras"):
        for tid, words in res["lda_palabras"].items():
            etiq = etiquetas_album.get(album,{}).get("lda",{}).get(tid,"—")
            print(f"    LDA T{tid}: [{etiq}] | {', '.join(words[:5])}")
    if res.get("nmf_palabras"):
        for tid, words in res["nmf_palabras"].items():
            etiq = etiquetas_album.get(album,{}).get("nmf",{}).get(tid,"—")
            print(f"    NMF T{tid}: [{etiq}] | {', '.join(words[:5])}")
    print()

# ── Análisis visual por álbum ─────────────────────────────────

def analisis_album(album):
    print(f"\n{'='*65}")
    print(f"  {album.upper()}")
    print(f"{'='*65}")

    tok_a  = tokens_df[tokens_df["album"] == album]
    corp_a = corpus_df[corpus_df["album"] == album]
    res    = resultados_album.get(album, {})
    color  = color_album(album)
    cat    = corp_a["categoria"].iloc[0] if not corp_a.empty else "—"
    año    = corp_a["año"].iloc[0] if not corp_a.empty else "—"

    print(f"  Categoría : {cat}  |  Año: {año}")
    print(f"  Canciones : {tok_a['id'].nunique()}  |  Tokens: {len(tok_a)}")

    # 1. Top 15 palabras
    top = tok_a["word"].value_counts().head(15).reset_index()
    top.columns = ["word","n"]
    fig_top = px.bar(top.sort_values("n"), x="n", y="word",
                     orientation="h",
                     title=f"Top 15 Palabras — {album}",
                     color_discrete_sequence=[color])
    fig_top.update_layout(plot_bgcolor="white", paper_bgcolor="white",
                          yaxis=dict(categoryorder="total ascending"))
    fig_top.show()

    # 2. TF-IDF — palabras distintivas del álbum vs corpus global
    docs_tfidf = tokens_df.groupby("album")["word"].apply(lambda x: " ".join(x))
    if len(docs_tfidf) >= 2:
        vec_tfidf = TfidfVectorizer(max_features=200)
        mat_tfidf = vec_tfidf.fit_transform(docs_tfidf)
        idx_album = list(docs_tfidf.index).index(album)
        scores    = mat_tfidf[idx_album].toarray().flatten()
        words_tf  = vec_tfidf.get_feature_names_out()
        tfidf_df  = (pd.DataFrame({"word":words_tf,"tfidf":scores})
                     .sort_values("tfidf",ascending=False)
                     .head(15))
        fig_tf = px.bar(tfidf_df.sort_values("tfidf"),
                        x="tfidf", y="word", orientation="h",
                        title=f"Palabras Distintivas TF-IDF — {album}",
                        color_discrete_sequence=[color])
        fig_tf.update_layout(plot_bgcolor="white", paper_bgcolor="white",
                             yaxis=dict(categoryorder="total ascending"))
        fig_tf.show()

    # 3. Wordcloud
    freq = dict(tok_a["word"].value_counts())
    if freq:
        wc = WordCloud(width=800, height=400, background_color="white",
                       colormap="viridis", max_words=80)
        wc.generate_from_frequencies(freq)
        plt.figure(figsize=(12,5))
        plt.imshow(wc, interpolation="bilinear")
        plt.axis("off")
        plt.title(f"Nube de Palabras — {album}",
                  fontsize=13, fontweight="bold")
        plt.tight_layout()
        plt.show()

    # 4. Tópicos LDA por álbum
    if res.get("lda_palabras"):
        print(f"\n── Tópicos LDA por álbum (k={NUM_TOPICS_ALBUM}) ──────")
        for tid, words in res["lda_palabras"].items():
            etiq = etiquetas_album.get(album,{}).get("lda",{}).get(tid,"—")
            print(f"  T{tid}: [{etiq}]  {' | '.join(words)}")
        print(f"  Coherencia Cv: {res['lda_coh']:.4f}")

    # 5. Tópicos NMF por álbum
    if res.get("nmf_palabras"):
        print(f"\n── Tópicos NMF por álbum (k={NUM_TOPICS_ALBUM}) ──────")
        for tid, words in res["nmf_palabras"].items():
            etiq = etiquetas_album.get(album,{}).get("nmf",{}).get(tid,"—")
            print(f"  T{tid}: [{etiq}]  {' | '.join(words)}")
        print(f"  Coherencia aprox: {res['nmf_coh']:.4f}")

    # 6. Tópicos globales asignados a las canciones de este álbum
    print(f"\n── Distribución de tópicos globales en este álbum ──")
    for col, etiquetas, nombre in [
        ("topico_lda_global",  etiquetas_lda,  "LDA"),
        ("topico_nmf_global",  etiquetas_nmf,  "NMF"),
        ("topico_bert_global", etiquetas_bert, "BERTopic"),
    ]:
        if col not in corp_a.columns: continue
        dist = corp_a[col].value_counts().reset_index()
        dist.columns = ["topico","n"]
        dist["etiqueta"] = dist["topico"].map(
            lambda t: etiquetas.get(int(t), f"T{t}") if pd.notna(t) else "—"
        )
        print(f"\n  {nombre}:")
        for _, row in dist.iterrows():
            print(f"    [{row['etiqueta']}] — {row['n']} canciones")

    # 7. Canciones del álbum con sus tópicos globales
    print(f"\n── Canciones y tópicos globales ─────────────────────")
    cols_show = ["cancion","topico_lda_global","topico_nmf_global",
                 "topico_bert_global"]
    cols_show = [c for c in cols_show if c in corp_a.columns]
    print(corp_a[cols_show].to_string(index=False))


# ── Ejecutar para todos los álbumes ──────────────────────────
for album in sorted(corpus_df["album"].unique()):
    analisis_album(album)

# ── Distribución de tópicos LDA por año ─────────────────────
topicos_tiempo = (corpus_df
                  .groupby(["año","topico_lda_global"])
                  .size()
                  .reset_index(name="n_canciones"))

topicos_tiempo["etiqueta"] = topicos_tiempo["topico_lda_global"].map(
    lambda t: etiquetas_lda.get(t, f"Tópico {t}")
)

fig = px.area(
    topicos_tiempo,
    x="año", y="n_canciones",
    color="etiqueta",
    title="Evolución de tópicos LDA a lo largo del tiempo",
    labels={"año":"Año de publicación","n_canciones":"Canciones","etiqueta":"Tópico"},
    line_group="etiqueta"
)
fig.update_layout(plot_bgcolor="white", paper_bgcolor="white",
                  xaxis=dict(dtick=2),
                  legend=dict(orientation="h", yanchor="bottom",
                              y=-0.4, xanchor="left", x=0))
fig.show()

# ── Evolución de tópicos a lo largo del tiempo — LDA, NMF, BERTopic ──

def grafica_evolucion(col_topico, etiquetas, titulo, color_scale="Plotly"):
    df_t = (corpus_df
            .groupby(["año", col_topico])
            .size()
            .reset_index(name="n_canciones"))
    df_t["etiqueta"] = df_t[col_topico].map(
        lambda t: etiquetas.get(int(t), f"Tópico {t}") if pd.notna(t) else "—"
    )
    fig = px.area(
        df_t, x="año", y="n_canciones", color="etiqueta",
        title=titulo,
        labels={"año":"Año de publicación",
                "n_canciones":"Canciones","etiqueta":"Tópico"},
        line_group="etiqueta",
        color_discrete_sequence=getattr(px.colors.qualitative, color_scale)
    )
    fig.update_layout(
        plot_bgcolor="white", paper_bgcolor="white",
        xaxis=dict(dtick=2),
        legend=dict(orientation="h", yanchor="bottom",
                    y=-0.5, xanchor="left", x=0)
    )
    fig.show()

grafica_evolucion(
    "topico_lda_global", etiquetas_lda,
    "Evolución de tópicos LDA a lo largo del tiempo"
)

grafica_evolucion(
    "topico_nmf_global", etiquetas_nmf,
    "Evolución de tópicos NMF a lo largo del tiempo",
    color_scale="Safe"
)

grafica_evolucion(
    "topico_bert_global", etiquetas_bert,
    "Evolución de tópicos BERTopic a lo largo del tiempo",
    color_scale="Pastel"
)

# ── Evolución de tópicos a lo largo del tiempo — LDA, NMF, BERTopic ──

def grafica_evolucion(col_topico, etiquetas, titulo, color_scale="Plotly"):
    df_t = (corpus_df
            .groupby(["año", col_topico])
            .size()
            .reset_index(name="n_canciones"))
    df_t["etiqueta"] = df_t[col_topico].map(
        lambda t: etiquetas.get(int(t), f"Tópico {t}") if pd.notna(t) else "—"
    )
    fig = px.line(
        df_t, x="año", y="n_canciones", color="etiqueta",
        title=titulo,
        labels={"año":"Año de publicación",
                "n_canciones":"Canciones","etiqueta":"Tópico"},
        markers=True,
        color_discrete_sequence=getattr(px.colors.qualitative, color_scale)
    )
    fig.update_layout(
        plot_bgcolor="white", paper_bgcolor="white",
        xaxis=dict(dtick=2),
        legend=dict(orientation="h", yanchor="bottom",
                    y=-0.5, xanchor="left", x=0)
    )
    fig.show()

grafica_evolucion(
    "topico_lda_global", etiquetas_lda,
    "Evolución de tópicos LDA a lo largo del tiempo"
)

grafica_evolucion(
    "topico_nmf_global", etiquetas_nmf,
    "Evolución de tópicos NMF a lo largo del tiempo",
    color_scale="Safe"
)

grafica_evolucion(
    "topico_bert_global", etiquetas_bert,
    "Evolución de tópicos BERTopic a lo largo del tiempo",
    color_scale="Pastel"
)

# ── Heatmap álbum × tópico global ────────────────────────────
# Muestra qué proporción de canciones de cada álbum pertenece a cada tópico

pivot = (corpus_df
         .groupby(["album","topico_lda_global"])
         .size()
         .reset_index(name="n")
         .pivot(index="album", columns="topico_lda_global", values="n")
         .fillna(0))

# Normalizar por álbum (proporción)
pivot_norm = pivot.div(pivot.sum(axis=1), axis=0).round(3)

# Ordenar álbumes por año
orden_año = (metadata_df.sort_values("año")["album"].tolist())
pivot_norm = pivot_norm.reindex([a for a in orden_año if a in pivot_norm.index])

# Renombrar columnas con etiquetas Gemini
pivot_norm.columns = [etiquetas_lda.get(c, f"T{c}") for c in pivot_norm.columns]

fig = px.imshow(
    pivot_norm,
    title="Heatmap: proporción de tópicos LDA por álbum (ordenado por año)",
    labels={"x":"Tópico","y":"Álbum","color":"Proporción"},
    color_continuous_scale="Blues",
    aspect="auto"
)
fig.update_layout(plot_bgcolor="white", paper_bgcolor="white", height=550)
fig.show()

# ── Línea temporal detallada ──────────────────────────────────
# Tópico dominante de cada álbum a lo largo del tiempo

topico_dom_album = (corpus_df
                    .groupby(["album","año"])["topico_lda_global"]
                    .agg(lambda x: x.value_counts().index[0])
                    .reset_index()
                    .rename(columns={"topico_lda_global":"topico_dominante"}))
topico_dom_album["etiqueta"] = topico_dom_album["topico_dominante"].map(
    lambda t: etiquetas_lda.get(t, f"Tópico {t}")
)
topico_dom_album = topico_dom_album.merge(
    clasificacion[["album","categoria"]], on="album", how="left"
)

fig = px.scatter(
    topico_dom_album,
    x="año", y="etiqueta",
    color="categoria",
    size_max=20,
    text="album",
    title="Tópico dominante por álbum a lo largo del tiempo (LDA)",
    labels={"año":"Año de publicación","etiqueta":"Tópico dominante"},
    color_discrete_map={
        "LENGUA_INDIGENA":  "#9b59b6",
        "ESPAÑOL_REGIONAL": "#3498db",
        "ESPAÑOL_ESTANDAR": "#2ecc71"
    }
)
fig.update_traces(textposition="top center", textfont_size=8)
fig.update_layout(plot_bgcolor="white", paper_bgcolor="white",
                  xaxis=dict(dtick=2), height=500)
fig.show()

# ── pyLDAvis — LDA global interactivo ────────────────────────
pyLDAvis.enable_notebook()
vis = gensimvis.prepare(lda_global, bow_g, dict_g)
pyLDAvis.display(vis)

# ── BERTopic — mapa 2D de tópicos ────────────────────────────
bertopic_global.visualize_topics()

# ── BERTopic — barchart de palabras por tópico ───────────────
bertopic_global.visualize_barchart(top_n_topics=k_lda_opt, n_words=8)

# ── Wordclouds por categoría lingüística ─────────────────────
categorias = corpus_df["categoria"].dropna().unique()
fig, axes  = plt.subplots(1, len(categorias), figsize=(18, 5))

for ax, cat in zip(axes, sorted(categorias)):
    ids_cat = corpus_df[corpus_df["categoria"]==cat]["id"].tolist()
    freq    = dict(tokens_df[tokens_df["id"].isin(ids_cat)]["word"].value_counts())
    if freq:
        wc = WordCloud(width=600, height=400, background_color="white",
                       colormap="viridis", max_words=60)
        wc.generate_from_frequencies(freq)
        ax.imshow(wc, interpolation="bilinear")
    ax.set_title(cat, fontsize=11, fontweight="bold")
    ax.axis("off")

plt.suptitle("Wordclouds por categoría lingüística", fontsize=13, fontweight="bold")
plt.tight_layout()
plt.show()

# ── Tabla resumen global ──────────────────────────────────────
resumen_global = (corpus_df
                  .groupby(["album","categoria","año"])
                  .agg(
                      n_canciones       =("cancion","count"),
                      n_tokens          =("n_tokens","sum"),
                      topico_lda        =("topico_lda_global",
                                          lambda x: x.value_counts().index[0]),
                      topico_nmf        =("topico_nmf_global",
                                          lambda x: x.value_counts().index[0]),
                      topico_bert       =("topico_bert_global",
                                          lambda x: x.value_counts().index[0]),
                  )
                  .reset_index()
                  .sort_values("año"))

resumen_global["etiqueta_lda"]  = resumen_global["topico_lda"].map(
    lambda t: etiquetas_lda.get(t, f"T{t}"))
resumen_global["etiqueta_nmf"]  = resumen_global["topico_nmf"].map(
    lambda t: etiquetas_nmf.get(t, f"T{t}"))
resumen_global["etiqueta_bert"] = resumen_global["topico_bert"].map(
    lambda t: etiquetas_bert.get(t, f"T{t}"))

print("══ RESUMEN GLOBAL POR ÁLBUM ══\n")
cols = ["album","categoria","año","n_canciones","n_tokens",
        "etiqueta_lda","etiqueta_nmf","etiqueta_bert"]
print(resumen_global[cols].to_string(index=False))

from sklearn.manifold import TSNE
from sentence_transformers import SentenceTransformer

# Obtener embeddings de cada canción (texto de tokens preprocesados)
print("Generando embeddings para visualización t-SNE...")
embed_viz = SentenceTransformer(SENTENCE_MODEL_NAME)
textos_viz = (tokens_df.groupby("id")["word"]
              .apply(lambda x: " ".join(x))
              .reset_index())
textos_viz.columns = ["id","texto_tokens"]

embeddings_viz = embed_viz.encode(
    textos_viz["texto_tokens"].tolist(),
    show_progress_bar=True
)

# Reducir a 2D con t-SNE
print("Reduciendo dimensiones con t-SNE...")
tsne = TSNE(n_components=2, random_state=42,
            perplexity=30, n_iter=1000)
coords = tsne.fit_transform(embeddings_viz)

# DataFrame con coordenadas y tópicos
viz_df = textos_viz[["id"]].copy()
viz_df["x"]  = coords[:, 0]
viz_df["y"]  = coords[:, 1]
viz_df = viz_df.merge(
    corpus_df[["id","cancion","album","categoria",
               "topico_lda_global","topico_nmf_global","topico_bert_global",
               "etiqueta_lda","etiqueta_nmf","etiqueta_bert"]],
    on="id", how="left"
)

# Gráfica 1 — coloreada por LDA
fig_tsne_lda = px.scatter(
    viz_df, x="x", y="y",
    color="etiqueta_lda",
    hover_data=["cancion","album","etiqueta_nmf","etiqueta_bert"],
    title="Espacio semántico — coloreado por tópico LDA",
    labels={"etiqueta_lda":"Tópico LDA"},
    color_discrete_sequence=px.colors.qualitative.Plotly
)
fig_tsne_lda.update_traces(marker=dict(size=8, opacity=0.8))
fig_tsne_lda.update_layout(plot_bgcolor="white", paper_bgcolor="white",
                            height=600)
fig_tsne_lda.show()

# Gráfica 2 — coloreada por NMF
fig_tsne_nmf = px.scatter(
    viz_df, x="x", y="y",
    color="etiqueta_nmf",
    hover_data=["cancion","album","etiqueta_lda","etiqueta_bert"],
    title="Espacio semántico — coloreado por tópico NMF",
    labels={"etiqueta_nmf":"Tópico NMF"},
    color_discrete_sequence=px.colors.qualitative.Safe
)
fig_tsne_nmf.update_traces(marker=dict(size=8, opacity=0.8))
fig_tsne_nmf.update_layout(plot_bgcolor="white", paper_bgcolor="white",
                            height=600)
fig_tsne_nmf.show()

# Gráfica 3 — coloreada por BERTopic
fig_tsne_bert = px.scatter(
    viz_df, x="x", y="y",
    color="etiqueta_bert",
    hover_data=["cancion","album","etiqueta_lda","etiqueta_nmf"],
    title="Espacio semántico — coloreado por tópico BERTopic",
    labels={"etiqueta_bert":"Tópico BERTopic"},
    color_discrete_sequence=px.colors.qualitative.Pastel
)
fig_tsne_bert.update_traces(marker=dict(size=8, opacity=0.8))
fig_tsne_bert.update_layout(plot_bgcolor="white", paper_bgcolor="white",
                             height=600)
fig_tsne_bert.show()

# Gráfica 4 — coloreada por categoría lingüística
fig_tsne_cat = px.scatter(
    viz_df, x="x", y="y",
    color="categoria",
    hover_data=["cancion","album","etiqueta_lda"],
    title="Espacio semántico — coloreado por categoría lingüística",
    color_discrete_map={
        "LENGUA_INDIGENA":  "#9b59b6",
        "ESPAÑOL_REGIONAL": "#3498db",
        "ESPAÑOL_ESTANDAR": "#2ecc71"
    }
)
fig_tsne_cat.update_traces(marker=dict(size=8, opacity=0.8))
fig_tsne_cat.update_layout(plot_bgcolor="white", paper_bgcolor="white",
                            height=600)
fig_tsne_cat.show()

print("Visualizaciones t-SNE generadas")

# Gráfica 1 — coloreada por LDA
fig_tsne_lda = px.scatter(
    viz_df, x="x", y="y",
    color="etiqueta_lda",
    hover_data=["cancion","album","etiqueta_nmf","etiqueta_bert"],
    title="Espacio semántico — coloreado por tópico LDA",
    labels={"etiqueta_lda":"Tópico LDA"},
    color_discrete_sequence=px.colors.qualitative.Plotly
)
fig_tsne_lda.update_traces(marker=dict(size=10, opacity=1))
fig_tsne_lda.update_layout(plot_bgcolor="white", paper_bgcolor="white",
                            height=600)
fig_tsne_lda.show()

# Gráfica 2 — coloreada por NMF
fig_tsne_nmf = px.scatter(
    viz_df, x="x", y="y",
    color="etiqueta_nmf",
    hover_data=["cancion","album","etiqueta_lda","etiqueta_bert"],
    title="Espacio semántico — coloreado por tópico NMF",
    labels={"etiqueta_nmf":"Tópico NMF"},
    color_discrete_sequence=px.colors.qualitative.Safe
)
fig_tsne_nmf.update_traces(marker=dict(size=10, opacity=1))
fig_tsne_nmf.update_layout(plot_bgcolor="white", paper_bgcolor="white",
                            height=600)
fig_tsne_nmf.show()

# Gráfica 3 — coloreada por BERTopic
fig_tsne_bert = px.scatter(
    viz_df, x="x", y="y",
    color="etiqueta_bert",
    hover_data=["cancion","album","etiqueta_lda","etiqueta_nmf"],
    title="Espacio semántico — coloreado por tópico BERTopic",
    labels={"etiqueta_bert":"Tópico BERTopic"},
    color_discrete_sequence=px.colors.qualitative.Pastel
)
fig_tsne_bert.update_traces(marker=dict(size=10, opacity=1))
fig_tsne_bert.update_layout(plot_bgcolor="white", paper_bgcolor="white",
                             height=600)
fig_tsne_bert.show()

# Gráfica 4 — coloreada por categoría lingüística
fig_tsne_cat = px.scatter(
    viz_df, x="x", y="y",
    color="categoria",
    hover_data=["cancion","album","etiqueta_lda"],
    title="Espacio semántico — coloreado por categoría lingüística",
    color_discrete_map={
        "LENGUA_INDIGENA":  "#9b59b6",
        "ESPAÑOL_REGIONAL": "#3498db",
        "ESPAÑOL_ESTANDAR": "#2ecc71"
    }
)
fig_tsne_cat.update_traces(marker=dict(size=8, opacity=0.8))
fig_tsne_cat.update_layout(plot_bgcolor="white", paper_bgcolor="white",
                            height=600)
fig_tsne_cat.show()

# Pureza por álbum — qué tan homogéneo es cada álbum en cada modelo
for col, nombre in [("topico_lda_global","LDA"),
                    ("topico_nmf_global","NMF"),
                    ("topico_bert_global","BERTopic")]:
    purezas = []
    for album, grupo in corpus_df.groupby("album"):
        conteos = grupo[col].value_counts()
        pureza  = conteos.iloc[0] / len(grupo)
        purezas.append(pureza)
    print(f"{nombre} — pureza promedio por álbum: {sum(purezas)/len(purezas):.3f}")

# ── Estabilidad BERTopic — múltiples runs ────────────────────
print(f"Calculando estabilidad BERTopic ({N_RUNS_ESTABILIDAD} runs)...\n")

def estabilidad_bertopic(n_runs=5):
    textos_bert_est = (tokens_df.groupby("id")["word"]
                       .apply(lambda x: " ".join(x)).tolist())

    # Los embeddings son deterministas — calcular una sola vez
    embed_est = SentenceTransformer(SENTENCE_MODEL_NAME)
    embeddings_est = embed_est.encode(textos_bert_est, show_progress_bar=False)

    asignaciones = []
    for seed in range(n_runs):
        # Variar semilla en UMAP y K-means
        umap_est = UMAP(n_neighbors=15, n_components=10,
                        min_dist=0.0, metric="cosine",
                        random_state=seed)
        kmeans_est = KMeans(n_clusters=k_bert_opt,
                            random_state=seed, n_init=10)
        bert_est = BERTopic(
            embedding_model=embed_est,
            umap_model=umap_est,
            hdbscan_model=kmeans_est,
            language="multilingual",
            calculate_probabilities=False,
            verbose=False,
            nr_topics=k_bert_opt,
        )
        topics_est, _ = bert_est.fit_transform(
            textos_bert_est, embeddings=embeddings_est
        )
        asignaciones.append(topics_est)
        print(f"  Run {seed+1}/{n_runs} completado")

    # Jaccard entre todos los pares de runs
    # (mismo método que LDA/NMF para comparabilidad)
    pares = [(i,j) for i in range(n_runs)
                   for j in range(i+1, n_runs)]
    sims = []
    for i, j in pares:
        set_i = frozenset(zip(range(len(asignaciones[i])),
                              asignaciones[i]))
        set_j = frozenset(zip(range(len(asignaciones[j])),
                              asignaciones[j]))
        # Usar ARI entre pares de runs como medida de estabilidad
        from sklearn.metrics import adjusted_rand_score
        sims.append(adjusted_rand_score(asignaciones[i],
                                        asignaciones[j]))

    return round(float(np.mean(sims)), 3)

estab_bert = estabilidad_bertopic(N_RUNS_ESTABILIDAD)
print(f"\n  BERTopic estabilidad : {estab_bert}")

# En la tabla comparativa, reemplaza "—" por el valor real
metricas_comparativa = pd.DataFrame([
    {"Modelo":"LDA",      "k":k_lda_opt,  "Coherencia":round(coh_lda_final,4),
     "Tipo_coh":"Cv real",     "Diversidad":div_lda_final,
     "Estabilidad":estab_lda,  "Outliers":"N/A"},
    {"Modelo":"NMF",      "k":k_nmf_opt,  "Coherencia":round(coh_nmf_final,4),
     "Tipo_coh":"Cv_aprox",    "Diversidad":div_nmf_final,
     "Estabilidad":estab_nmf,  "Outliers":"N/A"},
    {"Modelo":"BERTopic", "k":k_bert_opt, "Coherencia":"—",
     "Tipo_coh":"—",           "Diversidad":div_bert_final,
     "Estabilidad":estab_bert, "Outliers":n_outliers},
])

metricas_comparativa

# ── Coherencia aproximada BERTopic — similitud coseno ────────
print("Calculando coherencia aproximada BERTopic...\n")

def coh_bertopic_approx(bertopic_model, tokens_df_input, vec_global, tfidf_global, n=10):
    """
    Misma aproximación coseno que NMF:
    Para cada tópico, toma las top-n palabras y calcula
    la similitud coseno promedio entre sus vectores TF-IDF.
    """
    fn = vec_global.get_feature_names_out()
    scores = []

    for tid in sorted(palabras_bert.keys()):
        words = palabras_bert[tid][:n]

        # Buscar índices de esas palabras en el vocabulario TF-IDF
        valid_idx = []
        for w in words:
            arr = np.where(fn == w)[0]
            if len(arr) > 0:
                valid_idx.append(arr[0])

        if len(valid_idx) < 2:
            continue

        # Vector TF-IDF de cada palabra en el corpus
        vecs = tfidf_global[:, valid_idx].toarray().T
        sim  = cosine_similarity(vecs)
        np.fill_diagonal(sim, 0)
        scores.append(float(sim.mean()))

    return round(float(np.mean(scores)), 4) if scores else float("nan")

coh_bert_approx = coh_bertopic_approx(
    bertopic_global, tokens_df, vec_g, tfidf_g, n=10
)
print(f"  BERTopic coherencia aprox (coseno): {coh_bert_approx}")
print(f"  NMF     coherencia aprox (coseno): {coh_nmf_final}")
print(f"  LDA     coherencia Cv (real)      : {coh_lda_final}")
print("\n  Nota: BERTopic y NMF usan la misma aproximación —")
print("  son comparables entre sí pero no con el Cv de LDA.")

metricas_comparativa = pd.DataFrame([
    {"Modelo":"LDA",      "k":k_lda_opt,
     "Coherencia":round(coh_lda_final,4),   "Tipo_coh":"Cv real",
     "Diversidad":div_lda_final,             "Estabilidad":estab_lda,
     "Pureza":0.392,                         "Outliers":"N/A"},
    {"Modelo":"NMF",      "k":k_nmf_opt,
     "Coherencia":round(coh_nmf_final,4),   "Tipo_coh":"Cv_aprox coseno",
     "Diversidad":div_nmf_final,             "Estabilidad":estab_nmf,
     "Pureza":0.353,                         "Outliers":"N/A"},
    {"Modelo":"BERTopic", "k":k_bert_opt,
     "Coherencia":coh_bert_approx,          "Tipo_coh":"Cv_aprox coseno",
     "Diversidad":div_bert_final,            "Estabilidad":estab_bert,
     "Pureza":0.459,                         "Outliers":n_outliers},
])

print("\n══ TABLA COMPARATIVA FINAL ══\n")
print(metricas_comparativa.to_string(index=False))
print("\n  Guía de interpretación:")
print("  Coherencia  — mayor es mejor (tópicos más coherentes)")
print("  Diversidad  — mayor es mejor (tópicos más distintos entre sí)")
print("  Estabilidad — mayor es mejor (más reproducible entre runs)")
print("  Pureza      — mayor es mejor (respeta estructura por álbum)")
print("  Outliers    — menor es mejor (cobertura del corpus)")
print("\n  Nota: Cv real (LDA) y Cv_aprox coseno (NMF, BERTopic)")
print("  no son directamente comparables entre sí.")